<div class="section-brands">
  <div class="container">
    <div class="row">
      <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('section_brands')->toHtml(); ?>
    </div>
  </div>
</div>
<div class="page_footer">
  <div id="footer" class="footer-container layout2 footer">
    <div class="container">
    	<?php echo $this->getChildHtml("footer_static"); ?>
    </div>
  </div>
  <div class="footer-bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-6">
          <?php  echo $this->getLayout()->createBlock("Rokanthemes\Themeoption\Block\Customcss")->setTemplate("html/copyright.phtml")->toHtml() ?>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-6">
          <?php echo $this->getChildHtml("footer_payment"); ?>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="back-top" class="hidden-xs"><i class="fa fa-angle-up"></i></div>

<script type="text/javascript">
  require([
      'jquery',
      'mage/mage',
      'rokanthemes/owl'
    ], function ($) {
      'use strict';
    $( document ).ready(function() {
      $(".block-content.brandowl-play >ul").owlCarousel({
        items : 7,
        itemsDesktop : [1366, 5],
            itemsDesktopSmall : [991,3],
            itemsTablet : [767, 2],
            itemsMobile : [479, 1],
          navigation : true,
           afterAction: function(el){
           this.$owlItems.removeClass('first-active')
           this.$owlItems .eq(this.currentItem).addClass('first-active')  
          }
      });
    });
  });
</script>  