<div id="header" class="header-container">
	<div class="header-content">
		<div class="top-header">
			<div class="container">
				<div class="row">
					<div class="col-md-6 col-lg-6 hidden-xs hidden-sm">	
						<div class="top-bar-left">
							<div class="top-text-left"><?php echo $this->getChildHtml("top-left-static"); ?></div>
						</div>
					</div>
					<div class="col-xs-12 col-md-6 col-lg-6">
						<div class="top-bar-right">
							<?php echo $this->getChildHtml("store_language"); ?>
							<?php echo $this->getChildHtml("currency"); ?>
							<?php if(!$this->helper('Rokanthemes\Themeoption\Helper\Data')->isLoggedIn()){
								echo $this->getChildHtml("register_login"); 
								}
								else{
								?>	
								<div class="register-login">
									<a href="<?php echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getBaseUrl('customer/account/logout');?>"><?php echo __('Logout');?></a>
							 	</div>
							<?php } ?>
							<div class="top-info">
								<div class="top-account has-child">
									<?php echo $this->getChildHtml("top.links"); ?>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	    <div class="header">
	    	<div class="header_main">
		    	<div class="header-main">
	          		<div class="container">
	          			<div class="row">
				          	<div class="wp-header">
					            <div class="col-md-3 col-sm-3 col-xs-12">
									<?php echo $this->getChildHtml("logo"); ?>
								</div>
					            <div class="col-md-9 col-sm-9 col-xs-12 top-search">
						            <div class="mini-cart-wrapper">
							              <div class="mini-carts">
							                <?php echo $this->getChildHtml("minicart");?>
							              </div>
						             </div>
					                <?php echo $this->getChildHtml("topSearch");?>
					            </div>	
					        </div>	
					    </div>
			        </div>    
		    	</div>
		    </div>
		    <div class="header-control header-nav">
		    	<div class="container">
		    		<div class="row">
						<span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
						<div class="hidden-md hidden-lg hidden-sm menu_left_home1">
							<?php echo $this->getChildHtml("menu.vertical")?>
							<?php echo $this->getChildHtml("navigation-sections")?>
							<?php echo $this->getChildHtml("top.navigation.sections")?>
						</div>
						<div class="col-sm-12 hidden-xs">
							<div class="header-wrapper-sticky<?php echo (!$this->helper('Rokanthemes\Themeoption\Helper\Themeconfig')->isEnableStickyHeader()) ? '' : ' enabled-header-sticky'; ?>">
								<div class="container-header-sticky">
									<div class="logo-sticky"><a href="<?php echo $block->getUrl('');?>" title="<?php echo __('Logo');?>"><img src="<?php echo ($this->helper('Rokanthemes\Themeoption\Helper\Themeconfig')->getStickyLogoHeader() != '') ? $this->helper('Rokanthemes\Themeoption\Helper\Themeconfig')->getStickyLogoHeader() : $this->getViewFileUrl("images/logo_sticky.png");?>" alt="<?php echo __('Logo');?>"/></a></div>
									<div class="top-menu top-menu-sticky">
									  <?php echo $this->getChildHtml("custom.topnav"); ?>
									</div>
								</div>
							</div>
						</div>	
					</div>
				</div>
			</div>
	    </div>
	</div>
</div>

