<?php 
	use Magento\Framework\App\Action\Action;
	$category_load = $block->getCategory();
	if($category_load && strtotime($block->getConfig('end_date')) >= strtotime($block->getCurrentTime())){ 
		$image = 'new_products_content_widget_grid';
?>
<div class="super-deal">
	<div class="container">
		<div class="super-deal-header">
			<div class="row">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="supper-deal-title">
						<h2><?php echo $block->getConfig('title');?></h2>
						<p><?php echo $block->getConfig('description');?></p>
					</div>
				</div>
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="super-deal-countdown" data-date="<?php echo $block->getConfig('end_date');?>"></div>
				</div>
			</div>
		</div>
		<?php 
			$newItems =  $block->getProducts();
		?>
		<div class="super-deal-content">
			<div class="row">
				<?php
				foreach($newItems as $_item) {
					$productImage = $block->getImage($_item, $image);
				?>
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="item-deal-product">
						<div class="product-thumb">
							<a href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" class="product-thumb-link">
								<?php $productImageThumb = $block->getImage($_item, 'category_page_grid-1');?>
								<span class="first-thumb">
									<?php echo $productImage->toHtml(); ?>
								</span>
								<span class="second-thumb">
									<?php echo $productImageThumb->toHtml(); ?>
								</span>
							</a>
							<div class="product-info-cart">
								<div class="product-extra-link">
									<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
										<a href="#"
										   data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'
										   class="wishlist-link" data-action="add-to-wishlist"
										   title="<?php echo __('Add to Wishlist') ?>">
											<i class="fa fa-heart-o"></i>
										</a>
									<?php endif; ?>
									<?php if ($block->getAddToCompareUrl()): ?>
										<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
										<a href="#" class="compare-link"
										   data-post='<?php echo $compareHelper->getPostDataParams($_item);?>'
										   title="<?php echo __('Add to Compare') ?>">
											<i class="fa fa-toggle-on"></i>
										</a>
									<?php endif; ?>
									<div class="quickview-product quickview-product-fixed-inline">
										<a  data-role="quickview-button" data-id="<?php echo $_item->getId(); ?>" href="javascript: void(0);" data-href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_item->getId()) ?>" title="<?php echo __('Quick view');?>"><i class="fa fa-search"></i></a>
									</div>
								</div>
								<div class="actions-primary addcart-link">
								  <?php if ($_item->isSaleable()): ?>
									<?php
									  $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
									  $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()]);
									  $postParams = json_decode($postData, true);
									  ?>
									<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
									  <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
									  <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
									  <?php echo $block->getBlockHtml('formkey')?>
									  <button type="submit"
										  title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
										  class="btn btn-add-to-cart">
										<i class="fa fa-shopping-basket"></i>
										<?php echo $block->escapeHtml(__('Add to Cart')); ?>
									  </button>
									</form>
								  <?php else: ?>
									<?php if ($_item->getIsSalable()): ?>
									  <div class="stock available"><span><?php echo __('In stock') ?></span></div>
									<?php else: ?>
									  <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
									<?php endif; ?>
								  <?php endif; ?>
								</div>
							</div>
						</div>
						<div class="product-info">
							<h3 class="title-product"><a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
										   href="<?php echo $block->getProductUrl($_item) ?>"
										   class="product-item-link">
											<?php echo $block->escapeHtml($_item->getName()) ?>
										</a></h3>
							<div class="desc"><?php echo $block->softTrim($block->escapeHtml(strip_tags($_item->getShortDescription())), 70); ?></div>
							<div class="info-price-deal">
								<?php /* @escapeNotVerified */ echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getPriceDisplayCustom($block->getProductPrice($_item)) ?>
								<?php echo $block->showLableSalePrice($_item); ?>
							</div>
							<div class="deal-shop-social">
								<a href="<?php echo $block->getProductUrl($_item) ?>" class="deal-shop-link"><?php echo __('Shop now') ?></a>
								<div class="social-deal social-network">
									<ul>
										<li><a href="//www.facebook.com/sharer.php?u=<?php echo $block->getProductUrl($_item) ?>" onclick="return !window.open(this.href, 'Facebook', 'width=500,height=500')"><img alt="" src="<?php echo $block->getBaseUrlMediaCustom();?>images/home1/s1.png"></a></li>
										<li><a href="//twitter.com/home?status=<?php echo $block->getProductUrl($_item) ?>" onclick="return !window.open(this.href, 'Twitter', 'width=500,height=500')"><img alt="" src="<?php echo $block->getBaseUrlMediaCustom();?>images/home1/s2.png"></a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>89 
				<?php } ?>
			</div>
			<a href="<?php echo $category_load->getUrl();?>" class="view-all-deal" data-hover="<?php echo __('View All') ?>"><span><?php echo __('View All') ?></span></a>
		</div>
	</div>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'rokanthemes/timecircles'
    ], function ($) {
		$( document ).ready(function() {
			if($('.super-deal-countdown').length>0){
				$(".super-deal-countdown").TimeCircles({
					fg_width: 0.01,
					bg_width: 1.2,
					text_size: 0.07,
					circle_bg_color: "#ffffff",
					time: {
						Days: {
							show: true,
							text: "Days",
							color: "#f9bc02"
						},
						Hours: {
							show: true,
							text: "Hours",
							color: "#f9bc02"
						},
						Minutes: {
							show: true,
							text: "Mins",
							color: "#f9bc02"
						},
						Seconds: {
							show: true,
							text: "Secs",
							color: "#f9bc02"
						}
					}
				}); 
			}
		});
    });
</script>
<?php } ?>