<style>

body .filter-content .swatch-option, body .filter-content .swatch-attribute.color .swatch-attribute-options a .swatch-option {
    border:1px solid #0000003d;
}

.item-product .swatch-attribute-options {
   float: right;
    width: 56%;
}
.page-product-configurable select.swatch-select.shoes_eu_size option.disabled {
    display:none;
}

.products-grid .item-product:hover .product-info-cart {
    display: none;
}

.product.attribute.sku {
    display: none !important;
}

body .product-options-wrapper .swatch-option.text, body .swatch-option {
    border-radius: 50%!important;
}
.page-products .swatch-option {
    height: 30px;
}

body .swatch-attribute-options {
    margin-top: 10px;
}

.page-products .swatch-option.text { 
height:30px;
line-height: 20px;
}

.checkout-index-index .field .message.warning {
    display:none;
}
.price-label {display: none!important;}

.page-product-configurable span.price-container.price-final_price.tax.weee .price-label{
    display:none!important;
}

@media only screen and (min-width: 768px) {
   .page-products h3.title-product {
    padding-top:10px;
     height:70px;
}

.page-products .product-info-cart {
    background:transparent;
}



.page-products .product-info h3 :hover {
    color:#D43361!important;
}


.page-products button.btn-add-to-cart.addcart-link:hover {
    color:white;
} 
    
    
    
.ves-megamenu.menu-hover .subhover:hover .dropdown-menu {
    top: 40px!important;
}
}

.cms-home span.price-label {
    display:none!important;
}

.checkout-index-index .swatch-option {
    height: 30px;
}

.checkout-index-index span.swatch-option.text {
    width: 52px;
    padding-top: 9px;
}

@media only screen and (max-width: 768px) {


.catalog-category-view .quickview-product {
    display: none;
}

.catalog-category-view button.btn-add-to-cart.addcart-link {
    display: none;
}

.catalog-category-view .products-grid .item-product:hover .product-info-cart {
    display:none;
}

.title-product a:hover {
    color: #D43361;
}
}

.login-container .fieldset .label {
    display: block;
}

@media only screen and (max-width: 600px) {
.top-text-left {
    width: 100%!important;
}

span.free-shipp {
    display: none;
}
}


.fancybox-overlay.fancybox-overlay-fixed {
    display:none!important;
}

.fancybox-wrap.fancybox-desktop.fancybox-type-html.fancybox-opened {
    display:none!important;
}

.street legend span {
    display: block !important;
    color:#2f2f2f;
}

.ves-megamenu li.active>a {
 background: transparent !important;
}

@media only screen and (min-width: 479px) { 

    .mob-pre-ftr {
    display: none;
}
}


@media only screen and (max-width: 479px) { 
    .homedynamic3 {
    display:none;
}
.homebundle {
    display:none;
}

.homestaticprod2 {
    display:none;
}

.row.homeoutlet {display:none;}

.row.pre-ftr {display:none;}

.product-grid li {
    width: 50%;
    height:300px;
}
.product-grid .item-product:after {
    display:none;
}

}

.product-info-cart .product-extra-link .compare-link.action.tocompare {
    display:none!important;
}
a.action.tocompare.compare-link {
    display: none;
}



.header-mini-cart::before { 
    width:46px;
    position: absolute;
    height:40px;
    content: " ";
    background-image: url("https://zumbashop.gr/pub/media/wysiwyg/cart-bag.png");
    background-repeat: no-repeat;
}


.header-container .header-content .minicart-wrapper {
    border:none;
}


@media only screen and (min-width: 800px) {
.ves-megamenu .nav-item > a {
    padding:0px;
}
}

.checkout-cart-index span.swatch-option {
    height: 30px;
}

.checkout-cart-index span.swatch-option.text {
    width:34px;
    height:34px;
    font-size:13px!important;
}

.cms-home .swatch-option  {
    height: 30px;
}


@media only screen and (min-width: 988px) {
.cms-home .swatch-attribute-options {
    float: right;
    width: 56%;
}}
.homedynamic3 {
    padding-top:35px;
}
.row.homeoutlet {
    padding-bottom:40px;
}

.text-pre-footer {
    padding-top:15px;
}
a:visited{
    color:#D43361;
}

.cms-home  .swatch-attribute-options {
    margin-top: 0px;
}

.cms-home .swatch-attribute.le_size {
    display:none;
}

.ves-megamenu li.level0:hover > a {
    background: transparent;
}

body .swatch-option:not(.disabled):hover {
    background: #D43361;
}

.toolbar-products .modes .modes-mode.active {
    background: #D43361;
    border-color: #D43361;
}

.toolbar-products .modes .modes-mode:not(.active):hover {
    background: #D43361;
    border-color: #D43361;
}

#layered-ajax-list-products .wrapper.list.products-list .product-list li .product-info .info-price .price-box.price-final_price .price-container .price {
    color: #D43361;
}

.swatch-option.selected {
    outline: 2px solid #D43361;
}

#layered_ajax_price_attribute .ui-slider-horizontal {
    background: #D43361;
}

#layered_ajax_price_attribute .ui-slider .ui-slider-handle {
    background: #D43361;
}

#layered_ajax_price_attribute #layered_ajax_price_text {
    color: #D43361;
}

    .header-control
    {
        display:none;
    }
    .header {
    background: #ffffff!important;
}

.custommenu.navigation li.level0 > .level-top {
    color:black;
    font-weight:700;
}

.custommenu.navigation li.level0 > .level-top:hover {
    color:#d43361;
}


span.my-cart {
    color:black;
}

ul.header.links {
    background: transparent!important;
}

.top-account ul li:first-child a{
    color:#D43361;
}

.top-account ul li:first-child a:hover{
    color:#9C1A3F;
}

.header-container .header-content .minicart-wrapper:hover .header-mini-cart::before {
    color: #9C1A3F;
}

.header-container .header-content .minicart-wrapper .header-mini-cart::before {
    color: #D43361;
}

div#switcher-language a{
    color:#D43361;
}

.top-header .switcher .switcher-options strong {
    color:#D43361;
}

.top-header .switcher .switcher-options strong:focus {
    color:#D43361;
}


.nav-banner {
    padding: 0px;
}

.nav-banner .container {
    max-width:100%;
    padding: 0px;
}


.top-home-content {
     padding: 0px;
}


.row.full-content {
    padding:0 120px;
}

.banner_item_bg img{
    width:100%;
}

@media only screen and (max-width: 600px) {
.wp-header div{
    display:block;
}}


.displaymobile .col-xs-3{
    float:right;
}

.displaydesktop .col-md-3{
    float:right;
}
.displaymobile .minicart-wrapper {
    top:-70px!important;
}

.ves-megamenu {
    background: transparent!important;
}

body .owl-theme .owl-controls .owl-buttons > div:hover {
    background: #D43361;
    border-color: #D43361;
}

.ves-megamenu li.active>a {
    color: #D43361 !important;
}


</style>
<a name="top"></a>
<div id="bannerTop" class="bannerTop text-center active">
	<div class="container"><span class="btn-bannerTop">Close  x</span></div>  
    <a href="#" title="">
		<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('advertisement_bannerTop')->toHtml(); ?>
	</a>                  
</div>
<div id="header" class="header-container">
	<div class="header-content">
		<div class="top-header">
			<div class="container">
				<div class="row">
					<div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">	
						<div class="top-bar-left">
							<div class="top-text-left"><?php echo $this->getChildHtml("top-left-static"); ?></div>
						</div>
					</div>
					<div class="col-xs-12 col-md-6 col-lg-6">
						<div class="top-bar-right">
							<?php echo $this->getChildHtml("store_language"); ?>
							<?php echo $this->getChildHtml("currency"); ?>
							<?php if(!$this->helper('Rokanthemes\Themeoption\Helper\Data')->isLoggedIn()){
								echo $this->getChildHtml("register_login"); 
								}
								else{
								?>	
								<div class="register-login">
									<a href="<?php echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getBaseUrl('customer/account/logout');?>"><?php echo __('Logout');?></a>
							 	</div>
							<?php } ?>
							<div class="top-info">
								<div class="top-account has-child">
									<?php echo $this->getChildHtml("top.links"); ?>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	    <div class="header">
	    	<div class="header_main">
		    	<div class="header-main">
	          		<div class="container">
	          			<div class="row">
				          	<div class="wp-header">
					            <div class="col-md-3 col-sm-3 col-xs-9">
									<?php echo $this->getChildHtml("logo"); ?>
									


								</div>
					            
						             <div class="col-md-6 col-sm-9 col-xs-9">
						                 
					                <div class="top-menu top-menu-sticky">
									<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('my-menu')->toHtml();?>

									 
									</div></div>
							<div class="col-md-3 col-sm-3 col-xs-3 top-search">
						            <div class="mini-cart-wrapper">
							              <div class="mini-carts">
							                <?php echo $this->getChildHtml("minicart");?>
							              </div>
						             </div>
					        </div>
					        </div>	
					    </div>
			        </div>    
		    	</div>
		    </div>
		    <div class="header-control header-nav">
		    	<div class="container">
		    		<div class="row">
						<span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
					
						
						<div class="col-lg-3 hidden-md">
							<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('head_contact')->toHtml(); ?>
						</div>	
					</div>
				</div>
			</div>
	    </div>
	</div>
</div>



<script type="text/javascript">
  require([
      'jquery',
      'mage/mage',
      'rokanthemes/owl'
    ], function ($) {
      'use strict';
    $( document ).ready(function() {
       $(".btn-bannerTop").click(function(e){
			$('#bannerTop').hide();
       		return false;
   		});

    });
  });
  
</script>      
<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window, document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '968811530216601');
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=968811530216601&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->