<?php
/**
 * Copyright © 2015 RokanThemes.com. All rights reserved.

 * @author RokanThemes Team <contact@rokanthemes.com>
 */
?>
<?php
/**
 * Blog sidebar archive template
 *
 * @var $block \Rokanthemes\Blog\Block\Sidebar\Archive
 */
?>

<?php
	$_months = $block->getMonths();
?>
<?php if (count($_months)) { ?>
<div class="sidebar-left sidebar-post">
	<div class="widget widget-post-cat" data-bind="scope: 'blog-archive'">
		<h2 class="title-widget-post">
			<?php echo __('Archive') ?>
		</h2>
		<ul>
			<?php foreach ($_months as $time) { ?>
				<?php
					$title = $block->getMonth($time).' '.$block->getYear($time);
					$title = $block->escapeHtml($title, null, true);
				?>
				<li>
					<a title="<?php echo __('Archive %s', $title) ?>" class="archive-item-link" href="<?php echo $block->getTimeUrl($time) ?>">
						<?php echo $title; ?>
					</a>
				</li>

			<?php } ?>
		</ul>
	</div>
</div>
<?php } ?>