<?php
/**
 * Copyright © 2015 RokanThemes.com. All rights reserved.

 * @author RokanThemes Team <contact@rokanthemes.com>
 */
?>
<?php
/**
 * Blog sidebar categories template
 *
 * @var $block \Rokanthemes\Blog\Block\Sidebar\Categories
 */
?>

<?php $items = $this->getGroupedChilds(); ?>

<?php if (count($items)) { ?>
<div class="sidebar-left sidebar-post">
	<div class="widget widget-post-cat" data-bind="scope: 'categories'">
		<h2 class="title-widget-post">
			<?php echo __('Categories') ?>
		</h2>

		<ul class="accordion"  id="accordion-2">
		<?php
			$level = 0;
			$first = true;
			foreach($items as $item) {
				$newLevel = $item->getLevel();

				if ($level == $newLevel && !$first) {
					echo '</li>';
				}

				if ($level < $newLevel) {
					echo '<ul>';
				}

				if ($level > $newLevel) {
					for ($i = $level; $i > $newLevel; $i--){
						echo '</ul></li>';
					}
				}

				?>
					<li>
						<a href="<?php echo $item->getCategoryUrl() ?>">
							<?php echo $block->escapeHtml($item->getTitle()) ?>
						</a>
				<?php
				$level = $newLevel;
				$first = false;
			}
		?>
		</ul>
	</div>
</div>
<?php } ?>