<div class="top-home-content">
	<div class="container">
		<div class="row">
			 <div class="col-lg-2 col-md-3">
			 </div>
			<div class="col-lg-10 col-md-9 col-sm-12 col-xs-12">
				<div class="banner-slider-top slide1">
					<div class="row">
						<div class="col-xs-12 col-sm-8">
							<div class="banner-slider banner-slider1">
								<?php echo $this->getLayout()->createBlock('Rokanthemes\SlideBanner\Block\Slider')->setslider_id('homepage1slider')->toHtml(); ?>
							</div>
						</div>
						<div class="col-xs-12 col-sm-4">
							<div>
								<div class="list-ads1">
									<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('list_ads1')->toHtml(); ?>
								</div>
							</div>
						</div>
					</div>
				 </div>
				<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block_top')->toHtml(); ?>
			</div>
		</div>
	</div>
</div>
<div class="top-home-content">
	<div  class="container">
		<div class="row">
			<div class="col-lg-2 col-md-3 col-sm-12 col-xs-12 sidebar_left_home1">
			 	<div class="banner_left_1">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_left_home1')->toHtml();?>
				</div>
				<div class="new_product">
					<?php echo $block->getLayout()->createBlock('Rokanthemes\Newproduct\Block\Newproduct')->setTemplate('Rokanthemes_Newproduct::newproduct.phtml')->toHtml();?>
				</div>
				<div class="the_blog">
					<?php echo $block->getLayout()->createBlock('Rokanthemes\Blog\Block\Sidebar\Recent')->setTemplate('Rokanthemes_Blog::sidebar/slider.phtml')->toHtml();?>
				</div>
				<div class="top_rate">
					<?php echo $block->getLayout()->createBlock('Rokanthemes\Toprate\Block\Toprate')->setTemplate('Rokanthemes_Toprate::toprate.phtml')->toHtml();?> 
				</div>
				<div class="banner_left_2">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_left2_home1')->toHtml();?>
				</div>
				<div class="testi_monial">
					<?php echo $block->getLayout()->createBlock('Rokanthemes\Testimonials\Block\Testimonials')->setTemplate('Rokanthemes_Testimonials::slider.phtml')->toHtml();?>
				</div>
			</div>
			<div class="col-lg-10 col-md-9 col-sm-12 col-xs-12">
				<div class="hot-deal">
					<?php echo $block->getLayout()->createBlock('Rokanthemes\Superdeals\Block\ProductByCat')->setTemplate('Rokanthemes_Superdeals::category.phtml')->toHtml();?>
				</div>
				<div class="wrapper-bestseller cat">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category1_home1')->toHtml();?>
				</div>
				<div class="banner_mid_1">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_mid_home1')->toHtml();?>
				</div>
				<div class="wrapper-bestseller cat">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category2_home1')->toHtml();?>
				</div>
				<div class="banner_mid_2">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_mid2_home1')->toHtml();?>
				</div>
				<div class="wrapper-bestseller cat">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category3_home1')->toHtml();?>
				</div>
				<div class="banner_bottom">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_bottom_home1')->toHtml();?>
				</div>
				<div class="section-featured-categories">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('featured_categories')->toHtml(); ?>
				</div>

				<div class="wrapper-bestseller cat">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category4_home1')->toHtml();?>
				</div>
			</div>
		</div>
	</div>
</div>



<script type="text/javascript">
require([
		'jquery',
		'mage/mage',
		'rokanthemes/owl'
	], function ($) {
		'use strict';
	$( document ).ready(function() {
		$("ul.tabs li").click(function() {
			$(this).closest("ul").find("li").removeClass("active");
			$(this).addClass("active");
			$(this).closest(".common-tab-system-fixed").find(".tab_content").hide();
			$(this).closest(".common-tab-system-fixed").find(".tab_content").removeClass("animate1");
			var activeTab = $(this).attr("rel");
			$("#"+activeTab) .addClass("animate1");
			$("#"+activeTab).fadeIn();
		});
		//Close Service Box
		$('.close-service-box').on('click',function(event) {
			event.preventDefault();
			$('.banner-top-home').slideUp('slow');
		});
		
		if($('.category-brand-slider').length>0){
			$('.category-brand-slider').each(function(){
			  $(this).find('.wrap-item').owlCarousel({
				items: 1,
				itemsCustom: [
				[0, 2],
				[480, 2],
				[768, 1],
				[992, 1],
				[1200, 1]
				],
				pagination: false,
				navigation: true,
				autoPlay:true,
				navigationText:['<i class="fa fa-angle-left"></i>','<i class="fa fa-angle-right"></i>']
			  });
			});
		}
	});
});
</script>